[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.numpy", "python311Packages.pandas", "python311Packages.scikit-learn", "gcc", "zlib", "cmake", "pkg-config", "ninja", "openblas"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu torch>=2.1.0",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8080"
